# Fantasy Football Draft Analysis

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)
pd.set_option("display.max_rows", 150)

## Data Loading & Cleaning
This section loads in the last 3 seasons of fantasy data for both sides of the ball.<br>
It cleans things up a bit as well.

In [2]:
def tally_points_for_player(player):
    total = 0
    for scoring_key in scoring_system.keys():
        if scoring_key in player:
            temp = scoring_system[scoring_key] * player[scoring_key]
            #print(f'cat:{scoring_key},  stat:{player[scoring_key]}, points: {temp}')
            total += temp
    return total
# end of tally_points_for_player

scoring_system = {
    "pass_yards": .04,
    "pass_tds": 4,
    "pass_completions": 0,
    "pass_first_downs": 0,
    "rush_yards": .1,
    "rush_first_downs": 0,
    "rush_tds": 6,
    "receptions": 0.5,
    "receiving_yards": .1,
    "receiving_first_downs": 0,
    "receiving_tds": 6,
    "fumbles_lost": -2,
    "thrown_ints": -1,
    "2pts": 2,
    "Solo": 1.5,
    "Ast": 0.75,
    "TFL": 3,
    "PD": 3,
    "Int": 5,
    "Sk": 3,
    "FF": 4,
    "FR": 2,
    "return_yards": .1,
    "def_tds": 6
}

In [3]:
off_2021 = pd.read_csv('./2021-offensive-fantasy-results.csv')
off_2021.head(5)

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Jonathan Taylor*+\TaylJo02,IND,RB,22,17,17,0.0,0.0,0.0,0.0,0.0,332.0,1811.0,5.45,18.0,51.0,40.0,360.0,9.00,2.0,4.0,2.0,20,NaN,NaN,333.0,373.1,381.1,353.1,187.0,1,1.0
1,2,Cooper Kupp*+\KuppCo00,LAR,WR,28,17,17,0.0,1.0,0.0,0.0,0.0,4.0,18.0,4.50,0.0,191.0,145.0,1947.0,13.43,16.0,0.0,0.0,16,1.0,NaN,295.0,439.5,442.5,367.0,173.0,1,2.0
2,3,Deebo Samuel*+\SamuDe00,SFO,WR,25,16,15,1.0,2.0,24.0,1.0,0.0,59.0,365.0,6.19,8.0,121.0,77.0,1405.0,18.25,6.0,4.0,2.0,14,NaN,NaN,262.0,339.0,347.0,300.5,140.0,2,3.0
3,4,Josh Allen\AlleJo02,BUF,QB,25,17,17,409.0,646.0,4407.0,36.0,15.0,122.0,763.0,6.25,6.0,0.0,0.0,0.0,NaN,0.0,8.0,3.0,6,2.0,1.0,403.0,402.6,426.6,417.6,134.0,1,4.0
4,5,Austin Ekeler\EkelAu00,LAC,RB,26,16,16,0.0,0.0,0.0,0.0,0.0,206.0,911.0,4.42,12.0,94.0,70.0,647.0,9.24,8.0,4.0,3.0,20,2.0,NaN,274.0,343.8,352.8,308.8,128.0,2,5.0

In [4]:
def_2021 = pd.read_csv('./2021-defensive-player-stats.csv')
def_2021.head(5)

,Rk,Player,Tm,Age,Pos,G,GS,Int,Yds,TD,Lng,PD,FF,Fmb,FR,Yds.1,TD.1,Sk,Comb,Solo,Ast,TFL,QBHits,Sfty
0,1,Jordyn Brooks\BrooJo01,SEA,24,LB,17,17,0.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0,5.0,0.0,1.0,184.0,109.0,75.0,10.0,3.0,NaN
1,2,C.J. Mosley\MoslC.00,NYJ,29,LB,16,16,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,168.0,103.0,65.0,2.0,3.0,NaN
2,3,De'Vondre Campbell+\CampDe00,GNB,28,LB,16,16,2.0,15.0,0.0,13.0,5.0,2.0,0.0,1.0,3.0,0.0,2.0,146.0,102.0,44.0,6.0,6.0,NaN
3,4,Foyesade Oluokun\OluoFo00,ATL,26,MLB,17,17,3.0,80.0,0.0,56.0,6.0,1.0,0.0,0.0,0.0,0.0,2.0,192.0,102.0,90.0,4.0,7.0,NaN
4,5,Denzel Perryman*\PerrDe00,LVR,29,LB,15,15,0.0,0.0,0.0,0.0,3.0,1.0,0.0,2.0,1.0,0.0,0.0,154.0,102.0,52.0,5.0,3.0,NaN

In [5]:
off_2020 = pd.read_csv('./2020-offensive-fantasy-results.csv')
off_2020.head(5)

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Derrick Henry *+\HenrDe00,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3.0,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara*\KamaAl00,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1.0,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook*\CookDa01,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5.0,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams*+\AdamDa01,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1.0,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce*+\KelcTr00,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1.0,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0

In [6]:
def_2020 = pd.read_csv('./2020-defensive-player-stats.csv')
def_2020.head(5)

,Rk,Player,Tm,Age,Pos,G,GS,Int,Yds,TD,Lng,PD,FF,Fmb,FR,Yds.1,TD.1,Sk,Comb,Solo,Ast,TFL,QBHits,Sfty
0,1,Zach Cunningham\CunnZa00,HOU,26,LILB,16,16,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,164.0,106.0,58.0,7.0,4.0,NaN
1,2,Roquan Smith\SmitRo07,CHI,23,LILB,16,16,2.0,16.0,0.0,11.0,7.0,1.0,1.0,1.0,0.0,0.0,4.0,139.0,98.0,41.0,18.0,6.0,NaN
2,3,Devin White\WhitDe02,TAM,22,LILB,15,15,0.0,0.0,0.0,0.0,4.0,1.0,0.0,1.0,2.0,0.0,9.0,140.0,97.0,43.0,15.0,16.0,NaN
3,4,Neville Hewitt\HewiNe00,NYJ,27,RILB,16,16,0.0,0.0,0.0,0.0,4.0,1.0,0.0,1.0,17.0,0.0,2.0,134.0,91.0,43.0,6.0,4.0,NaN
4,5,Jordan Poyer\PoyeJo00,BUF,29,SS,16,16,2.0,14.0,0.0,14.0,5.0,2.0,0.0,0.0,0.0,0.0,2.0,124.0,91.0,33.0,4.0,4.0,NaN

In [7]:
off_2019 = pd.read_csv('./2019-offensive-fantasy-results.csv')
off_2019.head(5)

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att.1,Yds.1,Y/A,TD.1,Tgt,Rec,Yds.2,Y/R,TD.2,Fmb,FL,TD.3,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Christian McCaffrey*+\McCaCh01,CAR,RB,23,16,16,0,2,0,0,0,287,1387,4.83,15,142,116,1005,8.66,4,1.0,0,19,1.0,NaN,355.0,471.2,477.2,413.2,215.0,1,1.0
1,2,Lamar Jackson*+\JackLa00,BAL,QB,22,15,15,265,401,3127,36,6,176,1206,6.85,7,0,0,0,NaN,0,9.0,2,7,NaN,NaN,416.0,415.7,429.7,421.7,152.0,1,2.0
2,3,Derrick Henry *\HenrDe00,TEN,RB,25,15,15,0,0,0,0,0,303,1540,5.08,16,24,18,206,11.44,2,5.0,3,18,NaN,NaN,277.0,294.6,303.6,285.6,136.0,2,3.0
3,4,Aaron Jones\JoneAa00,GNB,RB,25,16,16,0,0,0,0,0,236,1084,4.59,16,68,49,474,9.67,3,3.0,2,19,NaN,NaN,266.0,314.8,322.8,290.3,125.0,3,4.0
4,5,Ezekiel Elliott*\ElliEz00,DAL,RB,24,16,16,0,0,0,0,0,301,1357,4.51,12,71,54,420,7.78,2,3.0,2,14,NaN,NaN,258.0,311.7,319.7,284.7,117.0,4,5.0

In [8]:
def_2019 = pd.read_csv('./2019-defensive-player-stats.csv')
def_2019.head(5)

,Rk,Player,Tm,Age,Pos,G,GS,Int,Yds,TD,Lng,PD,FF,Fmb,FR,Yds.1,TD.1,Sk,Comb,Solo,Ast,TFL,QBHits,Sfty
0,1,Budda Baker*\BakeBu00,ARI,23,FS,16,16,0.0,0.0,0.0,0.0,6.0,1.0,0.0,1.0,0.0,0.0,0.5,147.0,104.0,43.0,7.0,2.0,NaN
1,2,Zach Cunningham\CunnZa00,HOU,25,RILB,16,16,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,24.0,0.0,2.0,142.0,99.0,43.0,7.0,3.0,NaN
2,3,Blake Martinez\MartBl01,GNB,25,IL/LILB,16,16,1.0,22.0,0.0,22.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,155.0,97.0,58.0,5.0,3.0,NaN
3,4,Eric Reid\ReidEr00,CAR,28,SS,16,16,0.0,0.0,0.0,0.0,6.0,1.0,0.0,2.0,0.0,0.0,4.0,130.0,97.0,33.0,7.0,5.0,NaN
4,5,Jordan Hicks\HickJo00,ARI,27,RILB,16,16,3.0,64.0,0.0,48.0,6.0,2.0,0.0,1.0,0.0,0.0,1.5,150.0,93.0,57.0,11.0,7.0,NaN

In [9]:
def_all = [def_2021, def_2020, def_2019]
off_all = [off_2021, off_2020, off_2019]

In [10]:
def offensive_cleaner(off_year):
    'Function to clean offensive datasets'
    # note our system is half ppr, calling that system fpts
    off_year.rename(columns={"FantPt":"standard_fpts", 'FDPt': 'fpts'}, inplace=True)
    off_year['Player'] = off_year['Player'].apply(lambda x : x.split('\\')[0]).apply(lambda x: x.strip('*+'))
    off_year['fpts/g'] = round(off_year['fpts']/off_year['G'], 3)
    off_year['2pts'] = off_year['2PM'] + off_year['2PP']
    off_year.fillna(0, inplace=True)
    off_year.rename(columns={
        "FantPos":'Pos',
        "Yds":"pass_yards",
        "Yds.1":"rush_yards",
        "Yds.2":"receiving_yards",
        "TD":"pass_tds",
        "TD.1":"rush_tds",
        "TD.2":"receiving_tds",
        "TD.3":"rush/rec_tds",
        "Int":"thrown_ints",
        "Rec":"receptions",
        "FL":"fumbles_lost"}, inplace=True)
    off_year['SuperPos'] = 'Off'
    off_year.drop(['Rk', 'Age', 'Cmp', 'Att', 'Att.1', 'Y/A', 'Fmb', '2PP', '2PM', 'GS',
                  'standard_fpts', 'PPR', 'DKPt', 'PosRank', 'OvRank'], axis='columns', inplace=True)
    off_year['fpts2'] = off_year.apply(tally_points_for_player, axis=1)
    off_year.sort_values(by='fpts/g', inplace=True, ignore_index=True, ascending=False)
    # the above line was to confirm the offensive players points were correct

In [11]:
for idx, year in enumerate(off_all):
    offensive_cleaner(year)
    print('1 year done.')

1 year done.
1 year done.
1 year done.

In [12]:
off_2021.head(5)

,Player,Tm,Pos,G,pass_yards,pass_tds,thrown_ints,rush_yards,rush_tds,Tgt,receptions,receiving_yards,Y/R,receiving_tds,fumbles_lost,rush/rec_tds,fpts,VBD,fpts/g,2pts,SuperPos,fpts2
0,Josh Allen,BUF,QB,17,4407.0,36.0,15.0,763.0,6.0,0.0,0.0,0.0,0.00,0.0,3.0,6,417.6,134.0,24.565,3.0,Off,417.58
1,Justin Herbert,LAC,QB,17,5014.0,38.0,15.0,302.0,3.0,0.0,0.0,0.0,0.00,0.0,1.0,3,395.8,112.0,23.282,6.0,Off,395.76
2,Derrick Henry,TEN,RB,8,5.0,1.0,0.0,937.0,10.0,20.0,18.0,154.0,8.56,0.0,0.0,10,184.3,29.0,23.038,0.0,Off,182.30
3,Tom Brady,TAM,QB,17,5316.0,43.0,12.0,81.0,2.0,0.0,0.0,0.0,0.00,0.0,3.0,2,386.7,106.0,22.747,0.0,Off,386.74
4,Kyler Murray,ARI,QB,14,3787.0,24.0,10.0,423.0,5.0,0.0,0.0,7.0,0.00,0.0,0.0,5,310.5,32.0,22.179,0.0,Off,310.48

**Note:** I've rolled DL into LBs since we are using flex IDP.

In [13]:
def clean_position(position):
    position = str(position)
    last_two_letters = position[-2:len(position)].upper()
    if last_two_letters == "LB":
        return "LB"
    elif last_two_letters in ["SS", "CB", "FS", "DB"]:
        return "DB"
    elif last_two_letters in ["DE", "DT", "NT"]:
        return "LB"
    elif last_two_letters == "AN":
        return None
    else:
        return 'LB'

def defensive_cleaner(def_year):
    'Function to clean defensive datasets'
    def_year.fillna(0, inplace=True)
    def_year['return_yards'] = def_year['Yds'] + def_year['Yds.1']
    def_year['def_tds'] = def_year['TD'] + def_year['TD.1']
    def_year['Player'] = def_year['Player'].apply(lambda x : x.split('\\')[0]).apply(lambda x: x.strip('*+'))
    def_year['Pos'] = def_year['Pos'].astype(str)    
    def_year['Pos'] = def_year['Pos'].apply(clean_position)
    def_year['SuperPos'] = 'Def'
    def_year.rename(columns={
        'Fmb': 'fumbles_lost'}, inplace=True)
    def_year['fpts'] = def_year.apply(tally_points_for_player, axis=1)
    def_year['fpts/g'] = round(def_year['fpts']/def_year['G'],3)
    def_year.sort_values(by='fpts/g', inplace=True, ignore_index=True, ascending=False)
    def_year.drop(['Yds', 'TD', 'Yds.1', 'TD.1', 'Age', 'Rk', 
                   'GS', 'Lng', 'Comb', 'QBHits'], axis='columns', inplace=True)
    
    #def_players_2021 = def_players_2021[def_players_2021['Pos'] != "nan"]

In [14]:
for year in def_all:
    defensive_cleaner(year)
    print('1 year done.')

1 year done.
1 year done.
1 year done.

In [15]:
def_2021.head(5)

,Player,Tm,Pos,G,Int,PD,FF,fumbles_lost,FR,Sk,Solo,Ast,TFL,Sfty,return_yards,def_tds,SuperPos,fpts,fpts/g
0,T.J. Watt,PIT,LB,15,0.0,7.0,5.0,0.0,3.0,22.5,48.0,16.0,21.0,0.0,1.0,0.0,Def,261.60,17.440
1,Foyesade Oluokun,ATL,LB,17,3.0,6.0,1.0,0.0,0.0,2.0,102.0,90.0,4.0,0.0,80.0,0.0,Def,283.50,16.676
2,Jordyn Brooks,SEA,LB,17,0.0,5.0,0.0,0.0,1.0,1.0,109.0,75.0,10.0,0.0,5.0,0.0,Def,270.25,15.897
3,Eric Kendricks,MIN,LB,15,2.0,4.0,0.0,0.0,1.0,5.0,81.0,62.0,8.0,0.0,24.0,0.0,Def,233.40,15.560
4,Roquan Smith,CHI,LB,17,1.0,3.0,0.0,0.0,0.0,3.0,95.0,68.0,12.0,0.0,53.0,1.0,Def,263.80,15.518

In [16]:
def_2020.head(5)

,Player,Tm,Pos,G,Int,PD,FF,fumbles_lost,FR,Sk,Solo,Ast,TFL,Sfty,return_yards,def_tds,SuperPos,fpts,fpts/g
0,Devin White,TAM,LB,15,0.0,4.0,1.0,0.0,1.0,9.0,97.0,43.0,15.0,0.0,2.0,0.0,Def,267.95,17.863
1,Roquan Smith,CHI,LB,16,2.0,7.0,1.0,1.0,1.0,4.0,98.0,41.0,18.0,0.0,16.0,0.0,Def,280.35,17.522
2,Darius Leonard,IND,LB,14,0.0,7.0,3.0,1.0,2.0,3.0,86.0,46.0,7.0,0.0,3.0,0.0,Def,228.80,16.343
3,Grant Haley,NOR,LB,1,1.0,1.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,Def,16.25,16.250
4,Eric Kendricks,MIN,LB,11,3.0,6.0,0.0,0.0,0.0,0.0,69.0,38.0,4.0,0.0,0.0,0.0,Def,177.00,16.091

### Breaking into Individual Positions

In [17]:
def intraposition_rank(df):
    'helper function to create within position ranks'
    df = df[df['G'] > 12]
    df = df.reset_index(drop=True)
    df.index += 1
    df = df.reset_index()
    df = df.rename(columns={"index":"PosRank"})
    return df

def split_positions_off(year):
    'help function to split stats for a year into individual positions'
    rb = year[year['Pos'] == 'RB']
    rb = intraposition_rank(rb)
    
    wr = year[year['Pos'] == 'WR']
    wr = intraposition_rank(wr)

    te = year[year['Pos'] == 'TE']
    te = intraposition_rank(te)
    
    qb = year[year['Pos'] == 'QB']
    qb = intraposition_rank(qb)
    
    return rb, wr, te, qb
# end of split_positions_off

def split_positions_def(year):
    'help function to split stats for a year into individual positions'
    lb = year[year['Pos'] == 'LB']
    lb = intraposition_rank(lb)
    db = year[year['Pos'] == 'DB']
    db = intraposition_rank(db)
    
    return lb, db
# end of split_positions_def

In [18]:
rb_2021, wr_2021, te_2021, qb_2021 = split_positions_off(off_2021)
rb_2020, wr_2020, te_2020, qb_2020 = split_positions_off(off_2020)
rb_2019, wr_2019, te_2019, qb_2019 = split_positions_off(off_2019)

In [19]:
lb_2021, db_2021 = split_positions_def(def_2021)
lb_2020, db_2020 = split_positions_def(def_2020)
lb_2019, db_2019 = split_positions_def(def_2019)

In [20]:
lb_2021.head(5)

,PosRank,Player,Tm,Pos,G,Int,PD,FF,fumbles_lost,FR,Sk,Solo,Ast,TFL,Sfty,return_yards,def_tds,SuperPos,fpts,fpts/g
0,1,T.J. Watt,PIT,LB,15,0.0,7.0,5.0,0.0,3.0,22.5,48.0,16.0,21.0,0.0,1.0,0.0,Def,261.60,17.440
1,2,Foyesade Oluokun,ATL,LB,17,3.0,6.0,1.0,0.0,0.0,2.0,102.0,90.0,4.0,0.0,80.0,0.0,Def,283.50,16.676
2,3,Jordyn Brooks,SEA,LB,17,0.0,5.0,0.0,0.0,1.0,1.0,109.0,75.0,10.0,0.0,5.0,0.0,Def,270.25,15.897
3,4,Eric Kendricks,MIN,LB,15,2.0,4.0,0.0,0.0,1.0,5.0,81.0,62.0,8.0,0.0,24.0,0.0,Def,233.40,15.560
4,5,Roquan Smith,CHI,LB,17,1.0,3.0,0.0,0.0,0.0,3.0,95.0,68.0,12.0,0.0,53.0,1.0,Def,263.80,15.518

In [21]:
db_2021.head(5)

,PosRank,Player,Tm,Pos,G,Int,PD,FF,fumbles_lost,FR,Sk,Solo,Ast,TFL,Sfty,return_yards,def_tds,SuperPos,fpts,fpts/g
0,1,Kenny Moore,IND,DB,17,4.0,13.0,1.0,0.0,0.0,1.0,82.0,20.0,6.0,0.0,78.0,0.0,Def,229.80,13.518
1,2,Trevon Diggs,DAL,DB,16,11.0,21.0,0.0,0.0,0.0,0.0,43.0,9.0,0.0,0.0,142.0,2.0,Def,215.45,13.466
2,3,Jalen Ramsey,LAR,DB,16,4.0,16.0,1.0,0.0,1.0,0.0,62.0,15.0,9.0,0.0,49.0,0.0,Def,210.15,13.134
3,4,Logan Ryan,NYG,DB,15,0.0,8.0,2.0,0.0,1.0,1.0,77.0,40.0,2.0,0.0,0.0,0.0,Def,188.50,12.567
4,5,J.C. Jackson,NWE,DB,17,8.0,23.0,1.0,0.0,0.0,0.0,44.0,14.0,2.0,0.0,92.0,1.0,Def,210.70,12.394